# Generated by Django 4.2.5 on 2023-09-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True, unique=True, verbose_name='組織番号')),
                ('dept_code', models.CharField(max_length=255, null=True, unique=True, verbose_name='組織整列番号')),
                ('dept_parent_code', models.CharField(max_length=255, null=True, verbose_name='親組織整列番号')),
                ('path', models.CharField(max_length=255, null=True, unique=True, verbose_name='組織系列')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='組織名')),
            ],
            options={
                'verbose_name': '組織',
                'verbose_name_plural': '組織',
            },
        ),
    ]
