# Generated by Django 4.2.5 on 2023-09-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=255, null=True, verbose_name='社員番号')),
                ('department_code', models.CharField(max_length=255, null=True, verbose_name='組織番号')),
            ],
            options={
                'verbose_name': '所属組織',
                'verbose_name_plural': '所属組織',
            },
        ),
    ]
